# Generated by Django 4.2.3 on 2023-07-18 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploadApp", "0002_rename_user_uploadedfile_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
