# Generated by Django 4.2.3 on 2023-07-18 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploadApp", "0003_alter_uploadedfile_uploader"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
