# Generated by Django 4.2.3 on 2023-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadApp", "0004_uploadedfile_shared_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="description",
            field=models.TextField(blank=True, default="description", null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="title",
            field=models.CharField(default="title", max_length=100),
        ),
    ]
